on: [push]

jobs:
  soos-sca-analysis:
    name: SOOS SCA Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v4
      with:
          node-version: '20.17.0'
    - name: Run SOOS Scan
      uses: soos-io/soos-sca-github-action@5d0c97061362053846bc31080c4f4634f5c53fbd
      with:
        client_id: ${{ secrets.SOOS_QA_CLIENT_ID }}
        api_key: ${{ secrets.SOOS__QA_API_KEY }}
        project_name: "sca-githubActions-B-2"
        api_url: 'https://qa-api.soos.io/api/'
        sca_version: 4.2.1-pre.1
